print("Hello World!")
print ("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("Adewara moses")
print('this command will print one line')
print('this\n command\n will\n print\n multiple\n lines')